apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- ../../base
namePrefix: dev-
namespace: dev-pawn-service
labels:
- includeSelectors: true
  pairs:
    app: pawn-serivce-app
    env: dev

patches:
  - path: patch/deployment.yaml