apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fe/ingress.yaml
  - fe/service.yaml
  - fe/deployment.yaml
  - be/ingress.yaml
  - be/service.yaml
  - be/deployment.yaml